### ISSUE TITLE
 coraza-spoa / invalid or unsupported Perl syntax / 920120 / crs 3.3.4

### ISSUE THREAD

**Issue by amsnek** [corazawaf/coraza-spoa#35]
when compiling coraza-spoa / crs 3.3.4 -> I get the following error when running 

```
{"level":"fatal","ts":"2022-09-29T09:32:03.773Z","caller":"logger/logger.go:83","msg":"failed to compile rule (error parsing regexp: invalid or unsupported Perl syntax: `(?<`): FILES_NAMES|FILES \"@rx (?<!&(?:[aAoOuUyY]uml)|&(?:[aAeEiIoOuU]circ)|&(?:[eEiIoOuUyY]acute)|&(?:[aAeEiIoOuU]grave)|&(?:[cC]cedil)|&(?:[aAnNoO]tilde)|&(?:amp)|&(?:apos));|['\\\"=]\" \"id:920120,phase:2,block,t:none,t:urlDecodeUni,msg:'Attempted multipart/form-data bypass',logdata:'%{MATCHED_VAR}',tag:'application-multi',tag:'language-multi',tag:'platform-multi',tag:'attack-protocol',tag:'paranoia-level/1',tag:'OWASP_CRS',tag:'capec/1000/210/272',ver:'OWASP_CRS/3.3.4',severity:'CRITICAL',setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}'\""}
```

this seems similar to: https://github.com/corazawaf/coraza/issues/138

am I missing something?

**Comment by amsnek** [comment]
oh thanks, will try that right away

**Comment by amsnek** [comment]
do i need a diffrerent coraza.conf for this?
getting this error now:

```
# ./coraza-spoa_amd64 --config-file /etc/coraza-spoa/coraza.conf
panic: yaml: unmarshal errors:
  line 7: cannot unmarshal !!str `SecRule...` into config.Config

goroutine 1 [running]:
main.main()
        /build/work/coraza-spoa/cmd/main.go:34 +0x11a
```

**Comment by amsnek** [comment]
with V4 I get the following error now:

```
{"level":"fatal","ts":"2022-09-29T12:36:01.197Z","caller":"logger/logger.go:83","msg":"failed to compile rule (error parsing regexp: invalid nested repetition operator: `*+`): REQUEST_HEADERS:Accept \"!@rx ^(?:(?:\\*|[^\\\"(),\\/:;<=>?![\\x5c\\]{}]+)\\/(?:\\*|[^\\\"(),\\/:;<=>?![\\x5c\\]{}]+))(?:\\s*+;\\s*+(?:(?:charset\\s*+=\\s*+(?:\\\"?(?:iso-8859-15?|windows-1252|utf-8)\\b\\\"?))|(?:(?:c(?:h(?:a(?:r(?:s(?:e[^t\\\"(),\\/:;<=>?![\\x5c\\]{}]|[^e\\\"(),/:;<=>?![\\x5c\\]{}])|[^s\\\"(),/:;<=>?![\\x5c\\]{}])|[^r\\\"(),/:;<=>?![\\x5c\\]{}])|[^a\\\"(),/:;<=>?![\\x5c\\]{}])|[^h\\\"(),/:;<=>?![\\x5c\\]{}])|[^c\\\"(),/:;<=>?![\\x5c\\]{}])[^\\\"(),/:;<=>?![\\x5c\\]{}]*(?:)\\s*+=\\s*+[^(),/:;<=>?![\\x5c\\]{}]+)|;?))*(?:\\s*+,\\s*+(?:(?:\\*|[^\\\"(),\\/:;<=>?![\\x5c\\]{}]+)\\/(?:\\*|[^\\\"(),\\/:;<=>?![\\x5c\\]{}]+))(?:\\s*+;\\s*+(?:(?:charset\\s*+=\\s*+(?:\\\"?(?:iso-8859-15?|windows-1252|utf-8)\\b\\\"?))|(?:(?:c(?:h(?:a(?:r(?:s(?:e[^t\\\"(),\\/:;<=>?![\\x5c\\]{}]|[^e\\\"(),/:;<=>?![\\x5c\\]{}])|[^s\\\"(),/:;<=>?![\\x5c\\]{}])|[^r\\\"(),/:;<=>?![\\x5c\\]{}])|[^a\\\"(),/:;<=>?![\\x5c\\]{}])|[^h\\\"(),/:;<=>?![\\x5c\\]{}])|[^c\\\"(),/:;<=>?![\\x5c\\]{}])[^\\\"(),/:;<=>?![\\x5c\\]{}]*(?:)\\s*+=\\s*+[^(),/:;<=>?![\\x5c\\]{}]+)|;?))*)*$\" \"id:920600,phase:1,block,t:none,t:lowercase,msg:'Illegal Accept header: charset parameter',logdata:'%{MATCHED_VAR}',tag:'application-multi',tag:'language-multi',tag:'platform-multi',tag:'attack-protocol',tag:'paranoia-level/1',tag:'OWASP_CRS',ver:'OWASP_CRS/4.0.0-rc1',severity:'CRITICAL',setvar:'tx.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}'\""}
```

**Comment by amsnek** [comment]
@NullIsNot0 any idea regarding the last error on crs v4? 🙈

**Comment by jptosso** [comment]
Hey ! Sorry for the late response, we are currently working on this issue and providing crs with re2 tests to avoid this in the future. I will link this error to the pr

**Comment by amsnek** [comment]
thanks! i will keep it open until its resoved?

**Comment by NullIsNot0** [comment]
Somehow I have missed your posts here, @amsnek! Sorry for that!

I forgot to mention that you have to switch to [experimental](https://github.com/corazawaf/coraza-spoa/tree/experimental) branch. There's great new idea in experimental branch - one instance of SPOA can work with multiple CRS configurations. And it uses Coraza WAF v3 (still in early alpha) instead of v2 in main branch.

```
git clone https://github.com/corazawaf/coraza-spoa.git
cd coraza-spoa
git checkout experimental
docker compose build
docker compose up
```
And open [http://localhost:4000/?x=/etc/passwd](http://localhost:4000/?x=/etc/passwd) in browser to perform a request which gets blocked by the WAF.

Note: For now only request scanning works pretty stable, but respons scanning hangs up SPOE in some cases. I'll try to test these cases and fill an issue in a week or two.

**Comment by sts** [comment]
I think this should be resolved already.
